Recruiter_Manager/Models/Customer.cs
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Recruiter_Manager.Models
{
    public class Customer
    {
        [Key]
        public int Id { get; set; }
        [Display(Name = "First Name")]
        public string FirstName { get; set; }
        [Display(Name = "Last Name")]
        public string LastName { get; set; }
        public string Email { get; set; }
        [Display(Name="Phone Number")]
        public string PhoneNumber { get; set; }
        [NotMapped]
        public IEnumerable<Recruiter> Recruiters { get; set; }
        [NotMapped]
        public IEnumerable<JobPosting> JobPostings { get; set; }
        [NotMapped]
        public IEnumerable<Appointment> UpcomingAppointments { get; set; }

        [ForeignKey("IdentityUser")]
        public string IdentityUserId { get; set; }
        public IdentityUser IdentityUser { get; set; }
    }
}

Recruiter_Manager/Controllers/JobPostingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Recruiter_Manager.Contracts;
using Recruiter_Manager.Data;
using Recruiter_Manager.Models;

namespace Recruiter_Manager.Controllers
{
    public class JobPostingsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private IRepositoryWrapper _repo;

        public JobPostingsController(ApplicationDbContext context, IRepositoryWrapper repo)
        {
            _context = context;
            _repo = repo;
        }

        // GET: Recruiters
        public async Task<IActionResult> Index()
        {
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var customer = _repo.Customer.GetCustomer(userId);
            var applicationDbContext = _context.JobPostings.Where(r => r.CustomerId == customer.Id);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Recruiters/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var recruiter = await _context.JobPostings
                .Include(r => r.Customer)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (recruiter == null)
            {
                return NotFound();
            }

            return View(recruiter);
        }

        // GET: Recruiters/Create
        public IActionResult Create()
        {
            JobPosting job = new JobPosting();
            ViewData["CustomerId"] = new SelectList(_context.Customers, "Id", "Id");
            job.AppStatus = new SelectList(job.ApplicationStatuses, "Text", "Text");     
            return View(job);
        }

        // POST: Recruiters/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,JobTitle,InterviewerFirstName,InterviewerLastName,InterviewerEmail,InterviewerPhoneNumber,CompanyName,PostedComp,DateApplied,ApplicationStatus,RecruiterId,CustomerId")] JobPosting job)
        {
            if (ModelState.IsValid)
            {
                var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
                var customer = _repo.Customer.GetCustomer(userId);
                job.CustomerId = customer.Id;
                _context.Add(job);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index","Customers");
            }
            ViewData["CustomerId"] = new SelectList(_context.Customers, "Id", "Id", job.CustomerId);
            return View(job);
        }

        // GET: Recruiters/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var job = await _context.JobPostings.FindAsync(id);
            if (job == null)
            {
                return NotFound();
            }
            ViewData["CustomerId"] = new SelectList(_context.Customers, "Id", "Id", job.CustomerId);
            job.AppStatus = new SelectList(job.ApplicationStatuses, "Text", "Text");
            return View(job);
        }

        // POST: Recruiters/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,JobTitle,InterviewerFirstName,InterviewerLastName,InterviewerEmail,InterviewerPhoneNumber,CompanyName,PostedComp,DateApplied,ApplicationStatus,RecruiterId,CustomerId")] JobPosting job)
        {
            if (id != job.Id)
            {
                return NotFound();
            }
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var customer = _context.Customers.Where(c => c.IdentityUserId == userId).SingleOrDefault();
            var jobToUpdate = _repo.JobPosting.FindByCondition(j => j.Id == id).SingleOrDefault();
            jobToUpdate.Id = id;
            jobToUpdate.CustomerId = customer.Id;
            jobToUpdate = UpdateJobPosting(job, jobToUpdate);
            if (ModelState.IsValid)
            {
                try
                {
                    
                    _context.JobPostings.Update(jobToUpdate);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!JobPostingExists(job.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index", "Customers");
            }
            ViewData["CustomerId"] = new SelectList(_context.Customers, "Id", "Id", job.CustomerId);
            return RedirectToAction("Index","Customers");
        }

        // GET: Recruiters/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var job = await _context.JobPostings
                .Include(r => r.Customer)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (job == null)
            {
                return NotFound();
            }

            return View(job);
        }

        // POST: Recruiters/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var job = await _context.JobPostings.FindAsync(id);
            _context.JobPostings.Remove(job);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index","Customers");
        }

        private bool JobPostingExists(int id)
        {
            return _context.JobPostings.Any(e => e.Id == id);
        }
        private JobPosting UpdateJobPosting(JobPosting job, JobPosting jobToUpdate)
        {
            jobToUpdate.JobTitle = job.JobTitle;
            jobToUpdate.InterviewerFirstName = job.InterviewerFirstName;
            jobToUpdate.InterviewerLastName = job.InterviewerLastName;
            jobToUpdate.InterviewerEmail = job.InterviewerEmail;
            jobToUpdate.InterviewerPhoneNumber = job.InterviewerPhoneNumber;
            jobToUpdate.CompanyName = job.CompanyName;
            jobToUpdate.PostedComp = job.PostedComp;
            jobToUpdate.DateApplied = job.DateApplied;
            jobToUpdate.ApplicationStatus = job.ApplicationStatus;
            job.ConversationNotes = job.ConversationNotes;
            return jobToUpdate;
        }
    }
}

Recruiter_Manager/Controllers/RecruitersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Recruiter_Manager.Contracts;
using Recruiter_Manager.Data;
using Recruiter_Manager.Models;

namespace Recruiter_Manager.Controllers
{
    public class RecruitersController : Controller
    {
        private readonly ApplicationDbContext _context;
        private IRepositoryWrapper _repo;

        public RecruitersController(ApplicationDbContext context, IRepositoryWrapper repo)
        {
            _context = context;
            _repo = repo;
        }

        // GET: Recruiters
        public async Task<IActionResult> Index()
        {
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var customer = _repo.Customer.GetCustomer(userId);
            var applicationDbContext = _context.Recruiters.Where(r => r.CustomerId == customer.Id);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Recruiters/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var recruiter = await _context.Recruiters
                .Include(r => r.Customer)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (recruiter == null)
            {
                return NotFound();
            }

            return View(recruiter);
        }

        // GET: Recruiters/Create
        public IActionResult Create()
        {
            Recruiter recruiter = new Recruiter();
            ViewData["CustomerId"] = new SelectList(_context.Customers, "Id", "Id");
            return View(recruiter);
        }

        // POST: Recruiters/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FirstName,LastName,Email,PhoneNumber,CompanyName,CustomerId")] Recruiter recruiter)
        {
            if (ModelState.IsValid)
            {
                var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
                var customer = _repo.Customer.GetCustomer(userId);
                recruiter.CustomerId = customer.Id;
                _context.Add(recruiter);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index","Customers");
            }
            ViewData["CustomerId"] = new SelectList(_context.Customers, "Id", "Id", recruiter.CustomerId);
            return RedirectToAction("Index","Customers");
        }

        // GET: Recruiters/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var recruiter = await _context.Recruiters.FindAsync(id);
            if (recruiter == null)
            {
                return NotFound();
            }
            ViewData["CustomerId"] = new SelectList(_context.Customers, "Id", "Id", recruiter.CustomerId);
            return View(recruiter);
        }

        // POST: Recruiters/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FirstName,LastName,Email,PhoneNumber,CompanyName,CustomerId")] Recruiter recruiter)
        {
            if (id != recruiter.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(recruiter);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RecruiterExists(recruiter.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CustomerId"] = new SelectList(_context.Customers, "Id", "Id", recruiter.CustomerId);
            return View(recruiter);
        }

        // GET: Recruiters/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var recruiter = await _context.Recruiters
                .Include(r => r.Customer)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (recruiter == null)
            {
                return NotFound();
            }

            return View(recruiter);
        }

        // POST: Recruiters/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var recruiter = await _context.Recruiters.FindAsync(id);
            _context.Recruiters.Remove(recruiter);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RecruiterExists(int id)
        {
            return _context.Recruiters.Any(e => e.Id == id);
        }
    }
}

Recruiter_Manager/Views/Customers/Create.cshtml
@model Recruiter_Manager.Models.Customer

@{
    ViewData["Title"] = "Create | Recruiter Manager";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Customer</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Recruiter_Manager/Views/Customers/Delete.cshtml
@model Recruiter_Manager.Models.Customer

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Customer</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdentityUser)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdentityUser.Id)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Recruiter_Manager/Views/Customers/Details.cshtml
@model Recruiter_Manager.Models.Customer

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Customer</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdentityUser)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdentityUser.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Recruiter_Manager/Views/Customers/Edit.cshtml
@model Recruiter_Manager.Models.Customer

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Customer</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Recruiter_Manager/Views/Customers/Index.cshtml
@model Recruiter_Manager.Models.Customer

@{
    ViewData["Title"] = "Dashboard | Recruiter Manager";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
    <style>
        table {
            border-collapse: collapse;
            border-spacing: 0;
            width: 100%;
            border: 1px solid #ddd;
        }
        thead{
            background-color: #f2f2f2;
        }
        th, td {
            text-align: left;
            padding: 16px;
        }

        tr:nth-child(even) {
            background-color: #f2f2f2;
        }
    </style>
<h1>Dashboard</h1>
    <form class="salarySearch" method="get">
        <span class="form-group">
            <input id="JobTitle" class="JobTitle" name="JobTitle" placeholder="Job Title" />    
            <button id="submitSalarySearch" type="submit" value="Submit" class="btn btn-primary btn-sm" onclick="getSalariesByTitle()" style="border-radius: 3px; border-spacing: 3px;">Compare Salary</button>
        </span>      
    </form>
<div>
    <table id="salaryDisplay">
    </table>
</div>
</br>
<center><h5>Recruiters</h5></center>
<div>
    <table class="recruitertable" style="overflow-x: auto; overflow-y: auto;">
        <thead>
            <tr>
                <th>
                    <center>First Name</center>
                </th>
                <th>
                    <center>Last Name</center>
                </th>
                <th>
                    <center>Email</center>
                </th>
                <th>
                    <center>Phone Number</center>
                </th>
                <th>
                    <center>Company Name</center>
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Recruiters)
            {
                <tr>
                    <td>
                        <center>@Html.DisplayFor(modelItem => item.FirstName)</center>
                    </td>
                    <td>
                        <center>@Html.DisplayFor(modelItem => item.LastName)</center>
                    </td>
                    <td>
                        <center>@Html.DisplayFor(modelItem => item.Email)</center>
                    </td>
                    <td>
                        <center>@Html.DisplayFor(modelItem => item.PhoneNumber)</center>
                    </td>
                    <td>
                        <center>@Html.DisplayFor(modelItem => item.CompanyName)</center>
                    </td>
                    <td>
                        <a asp-controller="Recruiters" asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                        <a asp-controller="Recruiters" asp-action="Details" asp-route-id="@item.Id">Details</a> |
                        <a asp-controller="Recruiters" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
<p>
    <a asp-controller="Recruiters" asp-action="Create">Add New Recruiter</a>
</p>
<br />
<center><h5>Job Postings and Applications</h5></center>
<div>
    <table class="jobtable" style="overflow-x: auto; overflow-y: auto;">
        <thead>
            <tr>
                <th>
                    <center>Job Title</center>
                </th>
                <th>
                    <center>Company Name</center>
                </th>
                <th>
                    <center>Posted Compensation</center>
                </th>
                <th>
                    <center>Application Date</center>
                </th>
                <th>
                    <center>Application Status</center>
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.JobPostings)
            {
                <tr>
                    <td>
                        <center>@Html.DisplayFor(modelItem => item.JobTitle)</center>
                    </td>
                    <td>
                        <center>@Html.DisplayFor(modelItem => item.CompanyName)</center>
                    </td>
                    <td>
                        <center>@Html.DisplayFor(modelItem => item.PostedComp)</center>
                    </td>
                    <td>
                        <center>@Html.DisplayFor(modelItem => item.DateApplied)</center>
                    </td>
                    <td>
                        <center>@Html.DisplayFor(modelItem => item.ApplicationStatus)</center>
                    </td>
                    <td>
                        <a asp-controller="JobPostings" asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                        <a asp-controller="JobPostings" asp-action="Details" asp-route-id="@item.Id">Details</a> |
                        <a asp-controller="JobPostings" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    </td>
                    
                </tr>
            }
        </tbody>
    </table>
</div>
<p>
    <a asp-controller="JobPostings" asp-action="Create">Add Job Posting</a>
</p>
<center><h5>Upcoming Appointments</h5></center>
<div>
    <table class="apptTable" style="overflow-x: auto; overflow-y: auto;">
        <thead>
            <tr>
                <th>
                    <center>Appointment Date</center>
                </th>
                <th>
                    <center>Appointment Name</center>
                </th>
                <th>
                    <center>Appointment Details</center>
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.UpcomingAppointments)
            {
                <tr>
                    <td>
                        <center>@Html.DisplayFor(modelItem => item.AppointmentDate)</center>
                    </td>
                    <td>
                        <center>@Html.DisplayFor(modelItem => item.AppointmentName)</center>
                    </td>
                    <td>
                        <center>@Html.DisplayFor(modelItem => item.AppointmentDetails)</center>
                    </td>
                    <td>
                        <a asp-controller="Appointments" asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                        <a asp-controller="Appointments" asp-action="Details" asp-route-id="@item.Id">Details</a> |
                        <a asp-controller="Appointments" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    </td>

                </tr>
            }
        </tbody>
    </table>
</div>
<p>
    <a asp-controller="Appointments" asp-action="Create">Add New Appointment</a>
</p>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>